### ISSUE TITLE
Do you know about the existence of these repositories ?

### ISSUE THREAD

**Issue by AlphaHot** [xianzhez/Coding-Interview-101#1]
https://github.com/jwasham/coding-interview-university
https://github.com/ykushch/coding-interview
https://github.com/halyph/mind-flow/blob/master/2018/2018-12-28-tech-interview-coding-prep-res.md
https://github.com/partho-maple/coding-interview-gym

**Comment by xianzhez** [comment]
I know some of them. The first one is a very detailed one. I will add these resources to the doc. Thanks for your suggestion!
